name: Build QTrigdoppler executables

on:
  push:
    branches: [ main ]
  pull_request:
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile QTrigdoppler.py --exclude PyQt6 --splash images/splash.jpg

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: QTrigdoppler-${{ matrix.os }}
          path: dist/*
